#include<iostream>
using namespace std;

int main() {
	int result, num;

	cin>>result;	// First number

	cin>>num;	if(result < num)	result = num;
	cin>>num;	if(result < num)	result = num;
	cin>>num;	if(result < num)	result = num;
	cin>>num;	if(result < num)	result = num;
	cin>>num;	if(result < num)	result = num;
	cin>>num;	if(result < num)	result = num;
	cin>>num;	if(result < num)	result = num;
	cin>>num;	if(result < num)	result = num;
	cin>>num;	if(result < num)	result = num;

	cout<<result;

	return 0;
}